version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: epar-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: epar-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/epar-db

volumes:
  postgres-data:

